apiVersion: v1
kind: Pod
metadata:
  name: go-playground
  labels:
    some-label: go-playground-cicd
spec:
  containers:
  - name: golangci
    image: 888804278608.dkr.ecr.us-west-2.amazonaws.com/public/golangci/golangci-lint:v1.38.0-alpine
    command: ["tail", "-f", "/dev/null"]
    imagePullPolicy: Always
    env:
    - name: GOPRIVATE
      value: github.com/snapdocs
    - name: GOMODCACHE
      value: /go/pkg/mod
  - name: go16
    image: 888804278608.dkr.ecr.us-west-2.amazonaws.com/public/golang:1.16.1-buster
    command: ["tail", "-f", "/dev/null"]
    imagePullPolicy: Always
    env:
    - name: GOPRIVATE
      value: github.com/snapdocs
    - name: GOMODCACHE
      value: /go/pkg/mod
  - name: sonar
    image: 888804278608.dkr.ecr.us-west-2.amazonaws.com/thirdparty/sonar-scanner:latest
    command: ["tail", "-f", "/dev/null"]
    imagePullPolicy: Always
  - name: docker
    image: 888804278608.dkr.ecr.us-west-2.amazonaws.com/public/docker-awscli:0.1
    command: ["tail", "-f", "/dev/null"]
    imagePullPolicy: Always
    volumeMounts:
    - name: docker
      mountPath: /var/run/docker.sock
    - name: dockercfg
      mountPath: /root/.docker
  restartPolicy: "Never"

  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
        type: Socket
    - name: dockercfg
      emptyDir: {}